// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/shenaijia/dao/internal"
)

// internalCommunityUnionDao is an internal type for wrapping the internal DAO implementation.
type internalCommunityUnionDao = *internal.CommunityUnionDao

// communityUnionDao is the data access object for the table community_union.
// You can define custom methods on it to extend its functionality as needed.
type communityUnionDao struct {
	internalCommunityUnionDao
}

var (
	// CommunityUnion is a globally accessible object for table community_union operations.
	CommunityUnion = communityUnionDao{
		internal.NewCommunityUnionDao(),
	}
)

// Add your custom methods and functionality below.
