// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/shenaijia/dao/internal"
)

// internalCommunityDao is an internal type for wrapping the internal DAO implementation.
type internalCommunityDao = *internal.CommunityDao

// communityDao is the data access object for the table community.
// You can define custom methods on it to extend its functionality as needed.
type communityDao struct {
	internalCommunityDao
}

var (
	// Community is a globally accessible object for table community operations.
	Community = communityDao{
		internal.NewCommunityDao(),
	}
)

// Add your custom methods and functionality below.
