// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/shenaijia/dao/internal"
)

// internalProjectDao is an internal type for wrapping the internal DAO implementation.
type internalProjectDao = *internal.ProjectDao

// projectDao is the data access object for the table project.
// You can define custom methods on it to extend its functionality as needed.
type projectDao struct {
	internalProjectDao
}

var (
	// Project is a globally accessible object for table project operations.
	Project = projectDao{
		internal.NewProjectDao(),
	}
)

// Add your custom methods and functionality below.
