// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/shenaijia/dao/internal"
)

// internalTaskActionDao is an internal type for wrapping the internal DAO implementation.
type internalTaskActionDao = *internal.TaskActionDao

// taskActionDao is the data access object for the table task_action.
// You can define custom methods on it to extend its functionality as needed.
type taskActionDao struct {
	internalTaskActionDao
}

var (
	// TaskAction is a globally accessible object for table task_action operations.
	TaskAction = taskActionDao{
		internal.NewTaskActionDao(),
	}
)

// Add your custom methods and functionality below.
