// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/shenaijia/dao/internal"
)

// internalTaskStepDao is an internal type for wrapping the internal DAO implementation.
type internalTaskStepDao = *internal.TaskStepDao

// taskStepDao is the data access object for the table task_step.
// You can define custom methods on it to extend its functionality as needed.
type taskStepDao struct {
	internalTaskStepDao
}

var (
	// TaskStep is a globally accessible object for table task_step operations.
	TaskStep = taskStepDao{
		internal.NewTaskStepDao(),
	}
)

// Add your custom methods and functionality below.
