// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/shenaijia/dao/internal"
)

// internalTaskTypeDao is an internal type for wrapping the internal DAO implementation.
type internalTaskTypeDao = *internal.TaskTypeDao

// taskTypeDao is the data access object for the table task_type.
// You can define custom methods on it to extend its functionality as needed.
type taskTypeDao struct {
	internalTaskTypeDao
}

var (
	// TaskType is a globally accessible object for table task_type operations.
	TaskType = taskTypeDao{
		internal.NewTaskTypeDao(),
	}
)

// Add your custom methods and functionality below.
