// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/shenaijia/dao/internal"
)

// internalTaskDao is an internal type for wrapping the internal DAO implementation.
type internalTaskDao = *internal.TaskDao

// taskDao is the data access object for the table task.
// You can define custom methods on it to extend its functionality as needed.
type taskDao struct {
	internalTaskDao
}

var (
	// Task is a globally accessible object for table task operations.
	Task = taskDao{
		internal.NewTaskDao(),
	}
)

// Add your custom methods and functionality below.
