// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/shenaijia/dao/internal"
)

// internalTaskTemplateDao is an internal type for wrapping the internal DAO implementation.
type internalTaskTemplateDao = *internal.TaskTemplateDao

// taskTemplateDao is the data access object for the table task_template.
// You can define custom methods on it to extend its functionality as needed.
type taskTemplateDao struct {
	internalTaskTemplateDao
}

var (
	// TaskTemplate is a globally accessible object for table task_template operations.
	TaskTemplate = taskTemplateDao{
		internal.NewTaskTemplateDao(),
	}
)

// Add your custom methods and functionality below.
