// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/shenaijia/dao/internal"
)

// internalTaskStageDao is an internal type for wrapping the internal DAO implementation.
type internalTaskStageDao = *internal.TaskStageDao

// taskStageDao is the data access object for the table task_stage.
// You can define custom methods on it to extend its functionality as needed.
type taskStageDao struct {
	internalTaskStageDao
}

var (
	// TaskStage is a globally accessible object for table task_stage operations.
	TaskStage = taskStageDao{
		internal.NewTaskStageDao(),
	}
)

// Add your custom methods and functionality below.
