// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/shenaijia/dao/internal"
)

// internalTaskTempletDao is an internal type for wrapping the internal DAO implementation.
type internalTaskTempletDao = *internal.TaskTempletDao

// taskTempletDao is the data access object for the table task_templet.
// You can define custom methods on it to extend its functionality as needed.
type taskTempletDao struct {
	internalTaskTempletDao
}

var (
	// TaskTemplet is a globally accessible object for table task_templet operations.
	TaskTemplet = taskTempletDao{
		internal.NewTaskTempletDao(),
	}
)

// Add your custom methods and functionality below.
