// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/shenaijia/dao/internal"
)

// internalUserTypeDao is an internal type for wrapping the internal DAO implementation.
type internalUserTypeDao = *internal.UserTypeDao

// userTypeDao is the data access object for the table user_type.
// You can define custom methods on it to extend its functionality as needed.
type userTypeDao struct {
	internalUserTypeDao
}

var (
	// UserType is a globally accessible object for table user_type operations.
	UserType = userTypeDao{
		internal.NewUserTypeDao(),
	}
)

// Add your custom methods and functionality below.
